### PR TITLE
Add recursive methods for layers/tags

### PR DESCRIPTION
**Pull request by Withaust**

### CODE REVIEW

**Comment by mafiesto4** [comment]
I think it should be `API_FUNCTION()`

**Comment by Withaust** [comment]
> I think it should be `API_FUNCTION()`

Whoops, lemme change that.

**Comment by Withaust** [comment]
Fixed it, CI errors are unrelated to the PR.

**Comment by Withaust** [comment]
@mafiesto4 Fixed it, CI errors are unrelated to the issue though.

**Comment by Withaust** [comment]
@mafiesto4 Fixed

**Comment by Withaust** [comment]
I decided to also add recursive methods for tags, but I noticed that `String`/`StringView` versions of setting/getting tags have `/// [Deprecated in v1.5]` comments. This is a long standing topic that I never had the chance of asking about. How is deprecation handled? Should I consider simply removing them (considering we are on the 1.6 for a month now), or is this some sort of a unique compatibility issue?

**Comment by Withaust** [comment]
I also decided to extend recursive addition to the tags as well.

**Pull request merged**
