### PR TITLE
OnAwake before all OnStarts

### PR DESCRIPTION
**Pull request by honzapatCZ**
As proposed in discord. This calls all OnAwakes before all OnStarts.
Scripts can now properly setup themselfs and after that, they can talk to each other fully initialized.

### CODE REVIEW

**Comment by mafiesto4** [comment]
Cool, just 2 cents from my side:
- what about `PostSpawn` - called when someone spawns script at runtime - I guess it needs to call `OnAwake` too
- we gonna need to test this heavily!

**Comment by honzapatCZ** [comment]
> Cool, just 2 cents from my side:
> 
> * what about `PostSpawn` - called when someone spawns script at runtime - I guess it needs to call `OnAwake` too
> * we gonna need to test this heavily!

Oh, so that was the difference between load and spawn, ok so I should add it to the other too? Ok.

**Comment by mafiesto4** [comment]
`OnAwake` is also called by:
- `PrefabInstanceData::SynchronizePrefabInstances` 
- `Script::SetParent`

Those usages should be updated too.

**Comment by honzapatCZ** [comment]
> `OnAwake`

I think those usages are OK as they are now, this change only applies to stuff that is batch spawned(loading level, spawning prefab with children) etc.

**Comment by honzapatCZ** [comment]
Unfortunatly looks like another recursive function is needed as there is a bit more stuff happening after PostSpawn/PostLoad so scripts wont be able to for example destroy themself. Also on similiar note, if scripts are scene objects and have the BeginPlay why isn't OnStart triggered there? so Actors would just recurse that to children and scripts instead of having to managing scripts stuff too?

**Comment by mafiesto4** [comment]
Note to self: probably move OnStart (and first OnEnable) to be called after the whole scene setup when loading a level. So physics and all objects are initialized properly. (test it deeply)

**Comment by mafiesto4** [comment]
Thanks for your contribution. I implemented this by refactoring `PostLoad`/`PostSpawn` events into a single `Initialize` method so all `OnAwake` events are called before any `OnStart`/`OnEnable` which resolves the problem.

Changes: 3239150a610d38bccb9a93f786371ed7227fefda

Docs update: https://github.com/FlaxEngine/FlaxDocs/commit/134c73cf70e6224f5796b8f80771719926e9a6ea

**Pull request closed without merging**
