### PR TITLE
Update world transform of child objects once on change

### PR DESCRIPTION
**Pull request by GoaLitiuM**
Alternative fix for #1796 #1350

### CODE REVIEW

**Comment by mafiesto4** [comment]
It makes the mesh look fine but editing with gizmo is not accurate. Also, with current fix it supports skewing the meshes from multiple transformations being applied which is a nice feature. Ofc this fix has nice perf benefit.

Before:

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/caf403b8-5c6f-4304-90af-0f54c181ef80

After;

https://github.com/FlaxEngine/FlaxEngine/assets/3464853/9462203f-50b1-48f6-b85f-748d2df5c1db

**Comment by GoaLitiuM** [comment]
The performance was my main concern with the recent changes. I can't reproduce the issue in the second video. Maybe the gizmo rotation shouldn't change the whole transform of the actor? I can see all values including scale changing whenever I rotate the actor.

**Comment by GoaLitiuM** [comment]
@mafiesto4 Can you check if these Gizmo related changes fixes the unstable rotation?

**Comment by GoaLitiuM** [comment]
Closing this one, the performance concerns would go away if the cached actor `_transform` is used instead of recalculating the transform during rendering of the actors (in `StaticModel::Draw` and probably other places as well). The Gizmo change might be worth salvaging as it feels more stable and doesn't cause all transform values to change when rotating the actor along one axis.

**Pull request closed without merging**
