### PR TITLE
Transform gizmos

### PR DESCRIPTION
**Pull request by DaveTheGameDev**
Update look and feel of the transform gizmos
image
image
image

### CODE REVIEW

**Comment by DaveTheGameDev** [comment]
made the scale handle a sphere because I saw it done like that somewhere and thought it looked cool but I can change it back if needed.

Looks like making the wire a little thicker for pos and scale might be a good idea.

**Comment by DaveTheGameDev** [comment]
image

**Comment by W2Wizard** [comment]
Some nice looking gizmos!

**Comment by jb-perrier** [comment]
Is there a reason about closing your PR ?

**Comment by honzapatCZ** [comment]
@DaveTheGameDev  could you reopen this again?

**Pull request closed without merging**
