### PR TITLE
Added reordering lists and visject parameters.

### PR DESCRIPTION
**Pull request by Menotdan**
This PR adds the ability to reorder lists and graph parameters in visject graphs. I think the code is a bit messy so any suggestions or changes are appreciated.

### CODE REVIEW

**Comment by Tryibion** [comment]
Looks like LFS is failing because a .flax file has been included.

**Comment by Menotdan** [comment]
> Looks like LFS is failing because a .flax file has been included in the pr.

Yeah I think the problem was introduced when I merged some change from master a while back, not sure how to fix it though.

**Comment by mafiesto4** [comment]
Maybe merge `master` into this branch and revert that file changes to be from `master`? Then push this branch? Or remake PR as a fallback option.

**Comment by mafiesto4** [comment]
Or you can delete that file from the branch. I'll ensure it's not removed when mering to `master`.

**Comment by mafiesto4** [comment]
Merged in 892ab47b7a48ac8fde7e399853e0984d73ece936.

**Pull request closed without merging**
