### PR TITLE
Compacted UpdateTransform Matrix math

### PR DESCRIPTION
**Pull request by NoriteSC**
no change to visuals 
image
just a faster cache Transform calculation with is called every frame of control is moving

other
PingPong function for c++

### CODE REVIEW

**Comment by RuanLucasGD** [comment]
@NoriteSC what this changes makes ?

**Comment by NoriteSC** [comment]
> @NoriteSC what this changes makes ?

@RuanLucasGD 
the code will be just faster 
there is araund 30-60 operetors less

**Comment by mafiesto4** [comment]
Nice improvement but the rotation is not correctly applied and sheers the control:

image

**Comment by NoriteSC** [comment]
> Nice improvement but the rotation is not correctly applied and sheers the control:
> 
> image

i will look in to it and fix it

**Comment by NoriteSC** [comment]
@mafiesto4 done the fix 
image
the value **m1.M21** needs to be cashed
m1.**M21** = (m1.M21 * cos) + (_scale.Y * -sin);
m1.M22 = (m1.**M21** * sin) + (_scale.Y * cos);

**Comment by mafiesto4** [comment]
There is still a minor difference when compared to `master` branch for Sheer usage:

Before:
Screenshot_2023_11_10_15_48_46

After:
Screenshot_2023_11_10_15_50_05

**Comment by NoriteSC** [comment]
> There is still a minor difference when compared to `master` branch for Sheer usage:
> 
> Before: Screenshot_2023_11_10_15_48_46
> 
> After: Screenshot_2023_11_10_15_50_05

@mafiesto4
what are the values
on those UI controls ?
for rotacion and sheer
exc.

**Comment by mafiesto4** [comment]
Here is that test scene: [Scene.zip](https://github.com/FlaxEngine/FlaxEngine/files/13347090/Scene.zip)

**Comment by NoriteSC** [comment]
@mafiesto4 got it fixed 
the  _shear.XY was fliped

**Comment by mafiesto4** [comment]
Looks the same so ready to merge 👍

**Pull request merged**
