### PR TITLE
Fix fullscreen dx11/dx12.

### PR DESCRIPTION
**Pull request by jb-perrier**
Fix the fullscreen crash on dx11/dx12.
Little tweak, we can now use ALT + ENTER to go fullscreen !

#333

### CODE REVIEW

**Comment by honzapatCZ** [comment]
You sure it wasnt disabled intentionally? From the looks of it it seems like the code is specifically there to disable it.

**Comment by jb-perrier** [comment]
Since fullscreen works great now, i don't see any reason to not enable ALT + ENTER, it's a very common way to switch to fullscreen.

**Comment by honzapatCZ** [comment]
> Since fullscreen works great now, i don't see any reason to not enable ALT + ENTER, it's a common way to switch to fullscreen.

Well you removed some code which checks buffers or whatever, it would be good to know what that does.

**Comment by jb-perrier** [comment]
SetFullscreenState trigger a WM_SIZE event that is hooked by the window resizing code. So we don't need to manually resize buffers here ( that's why switching to fullscreen was not working before ).

**Comment by mafiesto4** [comment]
Tested and works great. Thnaks. I guess the previous behavior was trying to resize the window to the fullscreen size but Win32 layer handles this for us to some degree.

**Pull request merged**
