### PR TITLE
add play button actions, number of players

### PR DESCRIPTION
**Pull request by envision3d**
- add context menu support for toolstrip buttons
- add "Play Game" vs. "Play Scenes"
- add context menu for choosing play button action to toolstrip button
- add number of game client selection for cook & run
- add toolstrip button and context menu for cook & run
- add menu items for the above
- add editor option entries for saving user preferences for the above

build-launch

Potential icon for new toolstrip button attached.

### CODE REVIEW

**Comment by Tryibion** [comment]
So all of these options will be in 2 places? Under the `Game` menu and from a right click context menu from the tool strip? Is this correct?

**Comment by envision3d** [comment]
That's the intention, yes.  There was already some options accessible from both places (appropriately so in my opinion) so I followed suit.  I also added a `Stop Game` menu item under the `Game` menu for consistency.

**Comment by Tryibion** [comment]
Could all of the options be under the `Game` menu and not have 2 context menus?

**Comment by envision3d** [comment]
Actually, I misspoke.  Currently the `Play Game` / `Play Scene` menu is only located within the right-click context menu of the `Play` button, but it certainly could have a representation in the `Game` menu as well.

And sure, everything could just be in the `Game` menu, but a context menu was requested by a few people as a part of the feature request and in discord conversation.  I have no strong personal feelings one way or another.

**Pull request merged**
