### PR TITLE
Faster results with less allocate

### PR DESCRIPTION
**Pull request by GroophyLifefor**

### CODE REVIEW

**Comment by GroophyLifefor** [comment]
Linq has special allocate optimizations and you can get results faster with exceptions.

**Comment by GroophyLifefor** [comment]
This is a very small change and the effect will be very low, but there is a proverb in turkey, "drop by drop, it becomes a lake."

**Comment by stefnotch** [comment]
@GroophyLifefor 
Linq has special optimizations, because it's usually slower and much harder to optimise than a plain for loop.
Btw, check out Benchmark.NET if you want to profile minor code tweaks like that. Do keep in mind that Flax uses a different .NET runtime though.

**Comment by GroophyLifefor** [comment]
@stefnotch 
You're right sir, this pr useless, sorry mafiesto.

**Pull request closed without merging**
