### PR TITLE
SmoothDamp for Vector2 and Vector3

### PR DESCRIPTION
**Pull request by AndrejStojkovic**
Implemented the SmoothDamp function for Vector2 and Vector3 in C#.

### CODE REVIEW

**Comment by MineBill** [comment]
Hey, nice work! Since c++ is also a supported language for scripting, I think it's a nice idea to add SmoothDamp to c++ too. If you need help implementing it in c++ feel free to reach out on the discord server, I go by the same name.

**Comment by NoriteSC** [comment]
error CS0266: Cannot implicitly convert type 'double' to 'float'. An explicit conversion exists (are you missing a cast?)
 @AndrejStojkovic 
 just a info because vector can be a double or float u need to use "Real" type definiton

**Comment by AndrejStojkovic** [comment]
@NoriteSC Should be fixed now, can you run the tests?

**Comment by yjplapian** [comment]
Hey Andrej! I wonder if you can also add the SqrMagnitude and Magnitude for these vectors? I was about to do that in a PR myself, but I saw that you already edited the scripts

**Comment by AndrejStojkovic** [comment]
@yjplapian, there is already an implementation for magnitude and squared magnituted - it's Length and LengthSquared. But I implemented static functions for Length and LengthSquared so you can use them as Vector3.Length(vector).

**Comment by AndrejStojkovic** [comment]
Fixed the type casting issue, tests pass on forked repo. Ready for merge. 👍

**Review by NoriteSC — APPROVED** [review]

**Pull request merged**
