### PR TITLE
Fix `Transform::LocalToWorld` not applying rotation to scale properly

### PR DESCRIPTION
**Pull request by GoaLitiuM**
Alternative fix for #1796 #1350

### CODE REVIEW

**Comment by GoaLitiuM** [comment]
The math tests seems to fail, not sure if the tests itself are correct and doesn't account for the rotation and scale in children correctly.

**Comment by mafiesto4** [comment]
hmm it doesn't fix it properly to me.

Before:
image

After:
image

**Comment by GoaLitiuM** [comment]
Hmm, it seems to only work when the parent rotation is zeroed.

**Comment by GoaLitiuM** [comment]
Closing in favor of #2301

**Pull request closed without merging**
