### PR TITLE
Adding Convert feature to Actor context menu.

### PR DESCRIPTION
**Pull request by jb-perrier**
You can now convert an actor to another actor type.

Children, transform, tag, layer, ect ... are saved but you will need to re-add your scripts ( probably a later pull request ).

### CODE REVIEW

**Comment by mafiesto4** [comment]
Overall it's a very cool idea but I think we need to wrap it inside undo action and support moving scripts too.

**Comment by jb-perrier** [comment]
Ok, i will take a look at this. Just let it open.

**Comment by jb-perrier** [comment]
Now support undo actions & scripts.

Not totally clean, there is two errors on undo (but it works), i'm investigating this.

**Comment by jb-perrier** [comment]
Looks good to me, ready for review.

**Comment by mafiesto4** [comment]
Works great. I added some improvements and tweaks here: https://github.com/FlaxEngine/FlaxEngine/commit/96846ea2551561596f4abe3cf51d2bba0b3d9d68

**Pull request merged**
