### PR TITLE
Collections maintenance

### PR DESCRIPTION
**Pull request by mtszkarbowiak**
Each change is trivial. Fixing them ad-hoc negatively impacts my focus xD

### CODE REVIEW

**Comment by mtszkarbowiak** [comment]
This PR is supposed to be trivial. I'm going to use this branch to make more meaningful changes.

**Comment by mtszkarbowiak** [comment]
One more thing: Is there any specific predicate defining which methods are `FORCE_INLINE`d? Seems quite random to me.

**Comment by mtszkarbowiak** [comment]
@mafiesto4 Could you take a look on this PR?

**Comment by mtszkarbowiak** [comment]
I was thinking about inlining in debug builds the alloctor get function... Wouldn't it be beneficial to get rid of `IsEmpty`, `IsDeleted` and other bucket methods?

**Comment by mafiesto4** [comment]
> This PR is supposed to be trivial. I'm going to use this branch to make more meaningful changes.

Sure, good approach. I'll merge this one in master as it doesn't change external APIs that much.

> Is there any specific predicate defining which methods are FORCE_INLINEd? Seems quite random to me.

Usually, things that are small or could benefit from inlining (eg. compiler could improve memory access if code is inlined so data could stay in registers)

> I was thinking about inlining in debug builds the alloctor get function... Wouldn't it be beneficial to get rid of IsEmpty, IsDeleted and other bucket methods?

If it won't produce that much overhead code it might be worth it. Especially in perf-intense methods like `FindPosition` or `SetCapacity`

**Comment by mtszkarbowiak** [comment]
Thank you for merging this one. I'm on my way to deliver the rest.

**Pull request merged**
